id: PB54A4C79
initial_creation_type: ocr
source_metadata:
  volumes:
    0d91bbbacdaf479aad40db3181ce56cc:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: གཙུག་ཏོར་དྲི་མ་མེད་པར་སྣང་བའི་གཟུངས་བཀླག་ཅིང་མཆོད་རྟེན་བརྒྱ་རྩ་བརྒྱད་དམ་མཆོད་རྟེན་ལྔ་གདབ་པའི་ཆོ་ག་མདོ་སད་ལས་བསྡུས་པ།
      total_pages: 1044
      volume_number: 38
